import{defineConfig}from"vite";
import react from"@vitejs/plugin-react";
import{visualizer}from"rollup-plugin-visualizer";

export default defineConfig(({mode})=>({
  plugins:[
    react(),
    mode==="analyze"&&visualizer({
      filename:"stats.html",
      open:true,
      gzipSize:true,
      brotliSize:true
    })
  ].filter(Boolean),
  server:{
    port:5173
  },
  build:{
    sourcemap:false,
    minify:"terser",
    cssMinify:true,
    reportCompressedSize:true,
    terserOptions:{
      compress:{
        drop_console:true,
        drop_debugger:true,
        passes:2
      },
      mangle:true,
      format:{
        comments:false
      }
    },
    rollupOptions:{
      output:{
        entryFileNames:"assets/[hash].js",
        chunkFileNames:"assets/[hash].js",
        assetFileNames:"assets/[hash][extname]"
      }
    }
  }
}));